/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wisdomjframe;

import wisdomchallenge.*;

/**
 *
 * @author Ignacio Esparza
 */
public class JPuntajes extends javax.swing.JFrame {

    RegistroPuntaje rp = new RegistroPuntaje();
    Puntaje p = new Puntaje();

    /**
     * Creates new form Puntajes
     */
    public JPuntajes() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Puntaje");
        setResizable(false);
        setSize(550, 580);
        mostrarPuntajes();
    }

    private void mostrarPuntajes() {
        String [] pts = rp.imprimirPuntajes();
        puntaje1.setText(pts[0]);
        puntaje2.setText(pts[1]);
        puntaje3.setText(pts[2]);
        puntaje4.setText(pts[3]);
        puntaje5.setText(pts[4]);
        puntaje6.setText(pts[5]);
        puntaje7.setText(pts[6]);
        puntaje8.setText(pts[7]);
        puntaje9.setText(pts[8]);
        puntaje10.setText(pts[9]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        volverMenuPuntajes = new javax.swing.JButton();
        opciones = new javax.swing.JLabel();
        num1 = new javax.swing.JLabel();
        num2 = new javax.swing.JLabel();
        num3 = new javax.swing.JLabel();
        num4 = new javax.swing.JLabel();
        num5 = new javax.swing.JLabel();
        num6 = new javax.swing.JLabel();
        num7 = new javax.swing.JLabel();
        num8 = new javax.swing.JLabel();
        num9 = new javax.swing.JLabel();
        num10 = new javax.swing.JLabel();
        puntaje1 = new javax.swing.JLabel();
        puntaje2 = new javax.swing.JLabel();
        puntaje3 = new javax.swing.JLabel();
        puntaje4 = new javax.swing.JLabel();
        puntaje5 = new javax.swing.JLabel();
        puntaje6 = new javax.swing.JLabel();
        puntaje7 = new javax.swing.JLabel();
        puntaje8 = new javax.swing.JLabel();
        puntaje9 = new javax.swing.JLabel();
        puntaje10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/generalbg.png"))); // NOI18N
        jcMousePanel1.setMaximumSize(new java.awt.Dimension(550, 520));
        jcMousePanel1.setMinimumSize(new java.awt.Dimension(550, 520));

        volverMenuPuntajes.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        volverMenuPuntajes.setText("Volver");
        volverMenuPuntajes.setMaximumSize(new java.awt.Dimension(1071, 477));
        volverMenuPuntajes.setMinimumSize(new java.awt.Dimension(1071, 477));
        volverMenuPuntajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenuPuntajesActionPerformed(evt);
            }
        });

        opciones.setFont(new java.awt.Font("Diogenes", 0, 24)); // NOI18N
        opciones.setText("Puntajes");

        num1.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        num1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num1.setText("1");

        num2.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        num2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num2.setText("2");

        num3.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        num3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num3.setText("3");

        num4.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        num4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num4.setText("4");

        num5.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        num5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num5.setText("5");

        num6.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        num6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num6.setText("6");

        num7.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        num7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num7.setText("7");

        num8.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        num8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num8.setText("8");

        num9.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        num9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num9.setText("9");

        num10.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        num10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num10.setText("10");

        puntaje1.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        puntaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntaje1.setText("Puntaje 1");

        puntaje2.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        puntaje2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntaje2.setText("Puntaje 1");

        puntaje3.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        puntaje3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntaje3.setText("Puntaje 4");

        puntaje4.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        puntaje4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntaje4.setText("Puntaje 3");

        puntaje5.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        puntaje5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntaje5.setText("Puntaje 6");

        puntaje6.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        puntaje6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntaje6.setText("Puntaje 5");

        puntaje7.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        puntaje7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntaje7.setText("Puntaje 7");

        puntaje8.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        puntaje8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntaje8.setText("Puntaje 8");

        puntaje9.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        puntaje9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntaje9.setText("Puntaje 9");

        puntaje10.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        puntaje10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntaje10.setText("Puntaje 10");

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                .addComponent(num10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(puntaje10, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(puntaje9, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(puntaje8, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(puntaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(puntaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(puntaje4, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(puntaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(puntaje6, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(puntaje5, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(puntaje7, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(volverMenuPuntajes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(opciones)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1)
                    .addComponent(puntaje1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num2)
                    .addComponent(puntaje2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num3)
                    .addComponent(puntaje4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num4)
                    .addComponent(puntaje3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num5)
                    .addComponent(puntaje6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num6)
                    .addComponent(puntaje5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num7)
                    .addComponent(puntaje7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num8)
                    .addComponent(puntaje8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num9)
                    .addComponent(puntaje9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num10)
                    .addComponent(puntaje10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(volverMenuPuntajes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverMenuPuntajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenuPuntajesActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_volverMenuPuntajesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JPuntajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel num10;
    private javax.swing.JLabel num2;
    private javax.swing.JLabel num3;
    private javax.swing.JLabel num4;
    private javax.swing.JLabel num5;
    private javax.swing.JLabel num6;
    private javax.swing.JLabel num7;
    private javax.swing.JLabel num8;
    private javax.swing.JLabel num9;
    private javax.swing.JLabel opciones;
    private javax.swing.JLabel puntaje1;
    private javax.swing.JLabel puntaje10;
    private javax.swing.JLabel puntaje2;
    private javax.swing.JLabel puntaje3;
    private javax.swing.JLabel puntaje4;
    private javax.swing.JLabel puntaje5;
    private javax.swing.JLabel puntaje6;
    private javax.swing.JLabel puntaje7;
    private javax.swing.JLabel puntaje8;
    private javax.swing.JLabel puntaje9;
    private javax.swing.JButton volverMenuPuntajes;
    // End of variables declaration//GEN-END:variables
}
