/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wisdomjframe;
import wisdomchallenge.Nombre;
/**
 *
 * @author Ignacio Esparza
 */
public class InNombre extends javax.swing.JFrame {

    /**
     * Creates new form InNombre
     */
    public InNombre() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Nombre");
        setResizable(false);
        setSize(550, 580);
        nombreActualM();
    }
    public void nombreActualM(){
        Nombre n = new Nombre();
        nombreActual.setText("No eres "+n.mostrarNombre());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        ingresarNombre = new javax.swing.JButton();
        volverOpciones = new javax.swing.JButton();
        escribirNombre = new javax.swing.JTextField();
        opciones1 = new javax.swing.JLabel();
        NombreBanner = new javax.swing.JLabel();
        nombreActual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/generalbg.png"))); // NOI18N
        jcMousePanel1.setMaximumSize(new java.awt.Dimension(550, 520));
        jcMousePanel1.setMinimumSize(new java.awt.Dimension(550, 520));

        ingresarNombre.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        ingresarNombre.setText("Aceptar");
        ingresarNombre.setMaximumSize(new java.awt.Dimension(1071, 477));
        ingresarNombre.setMinimumSize(new java.awt.Dimension(1071, 477));
        ingresarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarNombreMouseClicked(evt);
            }
        });
        ingresarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarNombreActionPerformed(evt);
            }
        });

        volverOpciones.setFont(new java.awt.Font("Diogenes", 0, 18)); // NOI18N
        volverOpciones.setText("Volver");
        volverOpciones.setMaximumSize(new java.awt.Dimension(1071, 477));
        volverOpciones.setMinimumSize(new java.awt.Dimension(1071, 477));
        volverOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverOpcionesActionPerformed(evt);
            }
        });

        escribirNombre.setFont(new java.awt.Font("Diogenes", 0, 14)); // NOI18N
        escribirNombre.setText("Anonimo");

        opciones1.setFont(new java.awt.Font("Diogenes", 0, 24)); // NOI18N
        opciones1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        opciones1.setText("Ingrese Nombre");

        NombreBanner.setFont(new java.awt.Font("Diogenes", 0, 24)); // NOI18N
        NombreBanner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreBanner.setText("Nombre");

        nombreActual.setFont(new java.awt.Font("Diogenes", 0, 24)); // NOI18N
        nombreActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(NombreBanner))
                    .addComponent(escribirNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ingresarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volverOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(opciones1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(nombreActual, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(NombreBanner)
                .addGap(42, 42, 42)
                .addComponent(nombreActual, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(opciones1)
                .addGap(27, 27, 27)
                .addComponent(escribirNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ingresarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(volverOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarNombreActionPerformed

    private void volverOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverOpcionesActionPerformed
        Opciones o = new Opciones();
        o.setVisible(true);
        dispose();
    }//GEN-LAST:event_volverOpcionesActionPerformed

    private void ingresarNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarNombreMouseClicked
        String nombre = escribirNombre.getText();
        nombreActual.setText("Bienvenido "+nombre);
        Nombre n = new Nombre();
        n.registroNombre(nombre);
        
    }//GEN-LAST:event_ingresarNombreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InNombre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NombreBanner;
    private javax.swing.JTextField escribirNombre;
    private javax.swing.JButton ingresarNombre;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JLabel nombreActual;
    private javax.swing.JLabel opciones1;
    private javax.swing.JButton volverOpciones;
    // End of variables declaration//GEN-END:variables
}
